POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2021-28-02",
  "specialist": "MD Sintti P.",
  "description": "Bad situation",
  "type": "HealthCheck",
  "healthCheckRating": 3
}